### ISSUE TITLE
Glacier STD library reverse request

### ISSUE THREAD

**Issue by DronCode** [DronCode/ReHitman#10]
### Tasks

- [ ] Reverse ZSTDOBJ
- [ ] Reverse ZGEOM
- [ ] Reverse ZLIST
- [ ] Reverse ZREGTAB

### Implement API for ZLIST

- [ ] Implement ZLIST factory (like `ZLISTFactory<T>::create(size_t count)`)
- [ ] Implement ZLIST::add
- [ ] Implement ZLIST::remove
- [ ] Implement ZLIST::at
- [ ] Implement ZLIST::next
- [ ] Implement ZLIST::prev
- [ ] Implement ZLIST::size

ZLIST API could be used through wrapper or similar data structure. I guess we shouldn't simulate original API. Main goal of this is get easier access to Glacier's members without any `__asm` blocks in logic code.

### Implement API for ZSysMem allocator

- [ ] Implement `ZSysMem::allocate<T>()`
- [ ] Implement `ZSysMem::deallocate(void* pMem)` or `ZSysMem::deallocate<T>(T* ptr)`

**Comment by DronCode** [comment]
I'm trying to work with ZLIST but I got a few issues with it. First of all, I supposed that ZLIST is a linear data structure and this is the wrong idea. Therefore I will reverse all ZLIST API before continuing work with it. Also, the teleport editor development was delayed for the moment when ZLIST API will be reversed enough for work with it. 
And I have a note about ZREFTAB: I supposed that ZREFTAB was created together ZLIST but in common case, it isn't right.
