### ISSUE TITLE
Disable scripting in-game

### ISSUE THREAD

**Issue by DronCode** [DronCode/ReHitman#15]
### Intro

Hitman uses native C/C++ scripts for in-game behavior. 
It conflicts with the multiplayer concept. 
We must disable all scripting and take control of all entities before start multiplayer development.

### Tasks

- [ ] Detect ZScript::update(float dt) method
- [ ] Hook ZScript::update(float dt) and implement our logic
- [ ] Add AngelScript or LUA as scripting engine

### Extra tasks

- [ ] Implement serialization/deserialization of entities into binary packages or JSON

**Comment by githubsux** [comment]
Just do DisableScripts 1 smh how hard is that you're dumb as rocks whatever imma bout to violate this nigga
