### ISSUE TITLE
Modern cheat menu aka HM3InGameDebugger

### ISSUE THREAD

**Issue by DronCode** [DronCode/ReHitman#7]
**Introduction**

That interface is very buggy, also some functions, like Give all, Beam works awful. 
In PR #5 we are working under custom debug menu and these functions could be implemented there. 

**Subtasks:**

- [ ] Disable ZCheatMenu & Shift+C shortcut
- [ ] Reverse player inventory
- [ ] Implement method "give item"
- [ ] Implement method "give available items list"
- [ ] Fix bug with model loading (if we starts the game from custom scene part of models will not be loaded)
- [ ] Implement hooks on ZOSD class for full anxiety control on level
- [ ] Reverse animation system for custom animations viewer
- [ ] Implement teleport for player
- [ ] Implement assets preview
- [x] Implement load level not from ZIP package

**Comment by HHCHunter** [comment]
- Implement assets preview

> We may be able to use parts of already existing things, such as

  `Viewer`
  `CharacterViewer`
  `AnimationViewer`

-  Implement load level not from ZIP package

> The `LoadFilter` option in HitmanBloodMoney.ini allows us to load things directly. 
> Need to research if this is just individual files within files, anm etc etc.

>The DefaultScene option in HitmanBloodMoney.ini allow us to load into levels on game boot.
>We can load levels directly via calling the .gms file directly.

> For example we can load the main menu via
```	DefaultScene=HitmanBloodMoney.gms```
> Or a mission via
```		DefaultScene=M00_main.GMS```

		
This can be done by loading a .gms files instead of a zip package, this will require some reversing of .gms file and some research

![image](https://user-images.githubusercontent.com/18048891/74012157-77ef4600-4981-11ea-8d85-80dd5d7a43a1.png)

We can also redirect where the game expects the files to be using HitmanBloodMoney.ini
 - ScenesPath
	This is meant to be the full path to the scenes folder. A bit crashy.

**Comment by ipoopedmypantsuups** [comment]
Hey, are you guys still working on this? Be exciting to hear some news...
Also the new release of ReHitman seems to be missing a few features... 😢

**Comment by DronCode** [comment]
Hi.

Yes, I still working on it but I was on a little vacation)
The repository was moved here https://github.com/ReGlacier/ReHitman

ср, 14 апр. 2021 г. в 12:52, ipoopedmypantsuups ***@***.***>:
